Turn off ibss/client for upgrade and vice versa.

diff --git a/gluon-v14tov15-helper/files/lib/gluon/v14tov15-helper/v14tov15-helper b/gluon-v14tov15-helper/files/lib/gluon/v14tov15-helper/v14tov15-helper
--- a/gluon-v14tov15-helper/files/lib/gluon/v14tov15-helper/v14tov15-helper
+++ b/gluon-v14tov15-helper/files/lib/gluon/v14tov15-helper/v14tov15-helper
@@ -15,10 +15,12 @@
 echo "$0 successfully start at $(date +%y%m%d_%H%M)" > /tmp/v14_lastrun
 
 # if your script is dependend on autoupdater, do only uptate if its realy enabled!
-if [ $(uci get autoupdater.settings.enabled) = 0 ]; then 
-	echo "autoupdater not active - exit" > /tmp/v14_lastrun 
-	exit 1
-fi
+# -wusel, 20180825: As as last resort mechanism. we *will* force autoupate on
+# disconnected nodes.
+#if [ $(uci get autoupdater.settings.enabled) = 0 ]; then
+#	echo "autoupdater not active - exit" > /tmp/v14_lastrun
+#	exit 1
+#fi
 
 # check gw
 # quick and dirty do it 4 times every 30 seconds
@@ -34,8 +36,8 @@ if [ $gwl -eq 0 ]; then echo "find batctl gwl - exit4" >> /tmp/v14_lastrun; exit
 
 # check if freifunk as we know it is nearby
 # ffssid=$(uci get wireless.client_radio0.ssid) # fail with simplified ssid offline changer
-: ${ffssid:=freiburg.freifunk.net} # if for whatever reason ffssid is NULL, obviously not generic
-many=$(iwinfo phy0 scan |grep "$ffssid" | wc -l)
+: ${ffssid:=freifunk} # if for whatever reason ffssid is NULL, obviously not generic
+many=$(iwinfo phy0 scan |grep -i "$ffssid" | wc -l)
 
 # connect to freifunk and get dhcp lease
 if [ $many != 0 ]; then
@@ -53,9 +55,13 @@ if [ $many != 0 ]; then
 		uci set wireless.update_radio0.mode=sta
 		uci set wireless.update_radio0.macaddr=$foomac
 		uci set wireless.update_radio0.ssid=$ffssid
-	else 
+	    uci set wireless.ibss_radio0.disabled=1
+	    uci set wireless.client_radio0.disabled=1
+	else
 		echo "reactivate known update if and restart wifi" >> /tmp/v14_lastrun
 		uci set wireless.update_radio0.disabled=0
+    	uci set wireless.ibss_radio0.disabled=1
+	    uci set wireless.client_radio0.disabled=1
 	fi
 	# restart wifi and get ip 
 	wifi; sleep 5;
@@ -69,24 +75,19 @@ fi
 
 # in case dns doesnt work correctly
 # (sorry, not generic - so please adjust)
-echo "nameserver 10.60.0.100" >> /tmp/resolv.conf
+echo "nameserver 1.1.1.1" >> /tmp/resolv.conf
 echo "nameserver 4.2.2.2" >> /tmp/resolv.conf
-echo "nameserver 10.60.0.110" >> /tmp/resolv.conf
+echo "nameserver 9.9.9.9" >> /tmp/resolv.conf
 
 # failsafe hardcoded ip for updateservers
 # (sorry, not generic - so please adjust)
-if [ $(cat /etc/hosts|grep "fdf0:9bb:7814:a630::007"|wc -l) = 0 ]; then
-	echo "fdf0:9bb:7814:a630::007 firmware.fffr" >> /etc/hosts
+if [ $(cat /etc/hosts|grep "2a06:e881:1700:1:400:c0ff:fefb:e216"|wc -l) = 0 ]; then
+	echo "2a06:e881:1700:1:400:c0ff:fefb:e216 firmware.4830.org" >> /etc/hosts
+	echo "193.26.120.20 firmware.4830.org" >> /etc/hosts
 fi
 #if [ $(cat /etc/hosts|grep "2001:470:25:713::2"|wc -l) = 0 ]; then
 #	echo "2001:470:25:713::2 openfreiburg.de" >> /etc/hosts
 #fi
-if [ $(cat /etc/hosts|grep "178.254.39.111"|wc -l) = 0 ]; then
-        echo 178.254.39.111 openfreiburg.de >> /etc/hosts
-fi
-if [ $(cat /etc/hosts|grep "fdf0:9bb:7814:a630::b45b"|wc -l) = 0 ]; then
-        echo "fdf0:9bb:7814:a630::b45b 1.updates.services.fffr" >> /etc/hosts
-fi
 
 # here comes the funny part, regular
 # also means update server MUST be reachable as client
@@ -98,8 +99,10 @@ autoupdater -f
 # fails also if device memory is/was_ever full : i/o error
 if [ $(uci get wireless.update_radio0.disabled) = 0 ]; then
 	uci set wireless.update_radio0.disabled=1
+	uci set wireless.ibss_radio0.disabled=0
+	uci set wireless.client_radio0.disabled=0
 fi
 wifi
 logger "something strange happens - could not autoupdate via $0"
+echo "something strange happens - could not autoupdate via $0" >> /tmp/v14_lastrun
 exit 21
-
